// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teren.Infrastructure.Persistence;

#nullable disable

namespace Teren.Infrastructure.Migrations.Identity
{
    [DbContext(typeof(TerenIdentityDbContext))]
    [Migration("20260830183844_Identity")]
    partial class Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teren.Core.Entities.ActivationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeDisplay")
                        .HasColumnType("text")
                        .HasColumnName("code_display");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("code_hash");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<Guid?>("ConsumedDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumed_device_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_activation_code");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_activation_code_company_id");

                    b.HasIndex("ConsumedDeviceId")
                        .HasDatabaseName("ix_activation_code_consumed_device_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_activation_code_created_by_user_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_activation_code_live")
                        .HasFilter("consumed_at IS NULL AND superseded_at IS NULL");

                    b.ToTable("activation_code", null, t =>
                        {
                            t.HasCheckConstraint("ck_activation_code_display_cleared", "(consumed_at IS NULL AND superseded_at IS NULL) OR code_display IS NULL");
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.AdminAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_admin_audit_actor_user_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_admin_audit_company_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_admin_audit_created_at");

                    b.ToTable("admin_audit", (string)null);
                });

            modelBuilder.Entity("Teren.Core.Entities.AdminSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_session");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_session_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_admin_session_user_id");

                    b.ToTable("admin_session", (string)null);
                });

            modelBuilder.Entity("Teren.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sr")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_app_user_company_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_admin_has_email", "role = 'worker' OR email IS NOT NULL");

                            t.HasCheckConstraint("ck_app_user_company_scope", "(role = 'super_admin') = (company_id IS NULL)");

                            t.HasCheckConstraint("ck_app_user_email_normalised", "email IS NULL OR email = lower(btrim(email))");

                            t.HasCheckConstraint("ck_app_user_role", "role IN ('super_admin','company_admin','worker')");

                            t.HasCheckConstraint("ck_app_user_username_normalised", "username IS NULL OR username = lower(btrim(username))");

                            t.HasCheckConstraint("ck_app_user_worker_has_no_password", "role <> 'worker' OR password_hash IS NULL");

                            t.HasCheckConstraint("ck_app_user_worker_has_username", "role <> 'worker' OR username IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_device_company_id");

                    b.HasIndex("RevokedByUserId")
                        .HasDatabaseName("ix_device_revoked_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_device_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_user_id");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("Teren.Core.Entities.PasswordToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_token");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_token_user_id");

                    b.ToTable("password_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_password_token_purpose", "purpose IN ('invite','reset')");
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.ActivationCode", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activation_code_company");

                    b.HasOne("Teren.Core.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("ConsumedDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_activation_code_consumed_device");

                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activation_code_created_by_user");

                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activation_code_user");
                });

            modelBuilder.Entity("Teren.Core.Entities.AdminAudit", b =>
                {
                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_audit_actor_user");

                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_audit_company");
                });

            modelBuilder.Entity("Teren.Core.Entities.AdminSession", b =>
                {
                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_session_user");
                });

            modelBuilder.Entity("Teren.Core.Entities.AppUser", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_user_company");
                });

            modelBuilder.Entity("Teren.Core.Entities.Device", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_company");

                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_device_revoked_by_user");

                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_device_user");
                });

            modelBuilder.Entity("Teren.Core.Entities.PasswordToken", b =>
                {
                    b.HasOne("Teren.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_token_user");
                });
#pragma warning restore 612, 618
        }
    }
}
