#!/usr/bin/env bash
# Teren — one-command deploy.
#
#   deploy/deploy.sh                     build, ship, migrate, restart, verify (remote host)
#   deploy/deploy.sh --target local      the same sequence against Docker on this machine
#   deploy/deploy.sh --seed              also run the idempotent demo seed after migrating
#   deploy/deploy.sh --skip-build        redeploy the images already built
#   deploy/deploy.sh --down              stop the stack (local target only)
#   deploy/deploy.sh --skip-cors         do not touch the bucket's CORS configuration
#
# The order below is the whole point of this script, and it is not negotiable:
#
#   preflight -> build -> ship -> database up -> MIGRATE -> app up -> bucket CORS -> verify
#
# Migrations are their own step, run against a healthy database, before the new API starts.
# CLAUDE.md records that forgetting them has bitten twice — once killing the money path with a
# bare Npgsql "42703 column does not exist". A deploy that cannot forget is the fix; a container
# that migrates on start-up is not, because it re-attempts the schema change on every restart of
# a crash loop and two replicas race each other.
#
# WHAT IS AND IS NOT PROVEN. The --target local path has been executed end to end. The remote
# path has NOT: at the time of writing there is no VPS and no domain (deferred to C7), so
# everything below the "ship" step on a real host — ssh, docker load, ACME certificate issuance —
# is written but unexercised. That seam is marked in the code. Do not read the existence of this
# script as evidence that a deploy has ever happened.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "${here}/.." && pwd)"

target="remote"
do_build=1
do_seed=0
do_down=0
skip_cors=0
build_args=()

while [ $# -gt 0 ]; do
  case "$1" in
    --target)     target="$2"; shift 2 ;;
    --local)      target="local"; shift ;;
    --skip-build) do_build=0; shift ;;
    --seed)       do_seed=1; shift ;;
    --down)       do_down=1; shift ;;
    --skip-cors)  skip_cors=1; shift ;;
    --no-cache)   build_args+=(--no-cache); shift ;;
    -h|--help)    sed -n '2,25p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

case "$target" in
  local|remote) ;;
  *) echo "FATAL: --target must be 'local' or 'remote'" >&2; exit 2 ;;
esac

log()  { printf '\n==> %s\n' "$*"; }
note() { printf '    %s\n' "$*"; }
die()  { printf '\nFATAL: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------------------------
# Disk. This machine has run out of disk during a build before, which takes Docker down with it.
# A deploy that stops with "1.4 GB free" is worth more than one that dies halfway through a
# `docker load` and leaves a half-written image.
# ---------------------------------------------------------------------------------------------
# check_disk <minimum-GB> [--warn]
#   --warn  report and continue; without it, stop.
# Building images wants a few GB; starting containers that are already built wants very little,
# so the two callers pass different numbers. A single threshold would either wave a doomed build
# through or refuse a restart that would have been fine.
check_disk() {
  local minimum="$1"
  local mode="${2:-}"
  local avail_kb
  avail_kb="$(df -Pk "$repo" | awk 'NR==2 {print $4}')" || return 0
  local avail_gb=$(( avail_kb / 1024 / 1024 ))
  note "free disk: ${avail_gb} GB"
  if [ "$avail_gb" -lt "$minimum" ]; then
    if [ "$mode" = "--warn" ]; then
      note "WARNING: under ${minimum} GB free. Enough to start containers, not enough to build."
    else
      die "only ${avail_gb} GB free, and building images needs about ${minimum}. Reclaim space first (docker builder prune, docker image prune) and re-run."
    fi
  fi
}

# ---------------------------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------------------------
if [ "$target" = "local" ]; then
  env_file="${here}/.env.local"
  compose_files=(-f "${here}/docker-compose.prod.yml" -f "${here}/docker-compose.local.yml")

  # Generated, never committed: every value in it is a throwaway that guards nothing but this
  # laptop, exactly like appsettings.Development.json. Regenerate by deleting the file.
  if [ ! -f "$env_file" ]; then
    log "Writing ${env_file} (throwaway local values)"
    cat > "$env_file" <<'LOCALENV'
# GENERATED by deploy/deploy.sh --target local. Throwaway values for a laptop rehearsal of the
# production stack; nothing here guards anything. Delete this file to regenerate it.
TEREN_STACK=teren-localprod
TEREN_DOMAIN=localhost
TEREN_ACME_EMAIL=
TEREN_APP_ORIGIN=https://localhost:8443
TEREN_TZ=Europe/Belgrade

TEREN_API_IMAGE=teren-api:local
TEREN_WEB_IMAGE=teren-web:local

TEREN_DB_NAME=teren
TEREN_DB_USER=teren
TEREN_DB_PASSWORD=teren_local_prod_only

# MinIO inside the compose network for the API; https through the `media` proxy for the phone.
TEREN_STORAGE_ENDPOINT=http://minio:9000
TEREN_STORAGE_PUBLIC_ENDPOINT=https://localhost:9443
TEREN_STORAGE_ACCESS_KEY=teren
TEREN_STORAGE_SECRET_KEY=teren_local_prod_only
TEREN_STORAGE_BUCKET=teren-media
TEREN_STORAGE_REGION=us-east-1
TEREN_STORAGE_FORCE_PATH_STYLE=true
TEREN_STORAGE_DOCKER_NETWORK=teren-localprod_default

# Empty on purpose: the bundle carries no device token (D7/F9), so a value here would only
# provision a demo device row whose credential nobody holds. Activate a phone at /auth/activate.
TEREN_DEVICE_TOKEN=

TEREN_STT_AZURE_KEY=
TEREN_STT_AZURE_REGION=
TEREN_ANTHROPIC_API_KEY=

TEREN_REPORT_FROM_ADDRESS=izvestaj@teren.local
TEREN_REPORT_FROM_NAME=Teren
TEREN_REPORT_REPLY_TO=
TEREN_SMTP_HOST=mailpit
TEREN_SMTP_PORT=1025
TEREN_SMTP_SECURITY=None
TEREN_SMTP_USERNAME=
TEREN_SMTP_PASSWORD=

TEREN_HANGFIRE_USER=teren
TEREN_HANGFIRE_PASSWORD=teren_local_prod_only

TEREN_BACKUP_DIR=./.backups
TEREN_BACKUP_RETENTION_DAYS=30
TEREN_BACKUP_BUCKET=teren-backups

# Non-default ports throughout, so this stack cannot collide with the development one
# (docker compose up -d / dotnet run / ng serve keep their 5432, 9000, 9001, 1025, 8025, 5080,
# 4200). Caddy listens on 8443 INSIDE the container too — the site address carries the port.
TEREN_HTTP_PUBLISH=127.0.0.1:8080:80
TEREN_HTTPS_PUBLISH=127.0.0.1:8443:8443
TEREN_HTTPS_PUBLISH_UDP=127.0.0.1:8443:8443/udp
TEREN_CADDYFILE=./Caddyfile.local
LOCALENV
  fi
else
  env_file="${here}/.env"
  compose_files=(-f "${here}/docker-compose.prod.yml")
  [ -f "$env_file" ] || die "no ${env_file}. Copy deploy/.env.example to deploy/.env and fill it in."
fi

# shellcheck disable=SC1090
set -a; . "$env_file"; set +a

compose_local() { docker compose --env-file "$env_file" "${compose_files[@]}" "$@"; }

if [ "$do_down" -eq 1 ]; then
  [ "$target" = "local" ] || die "--down is only supported for --target local; stopping a real box is a decision, not a flag."
  log "Stopping the local stack"
  compose_local down
  exit 0
fi

# ---------------------------------------------------------------------------------------------
# 1. Preflight — everything that can be wrong before anything has changed
# ---------------------------------------------------------------------------------------------
log "1/7 Preflight"
check_disk 1 --warn
docker info >/dev/null 2>&1 || die "Docker is not running."

# TEREN_DEVICE_TOKEN is deliberately NOT here. Since D7/F9 the PWA bundle carries no token at
# all, so this value is only the *demo device's* server-side credential; empty means "provision no
# demo device", which is a working host, not a broken one (see the note further down).
#
# TEREN_APP_ORIGIN moved into this list on 2026-09-04, and out of the remote-only block below.
# It stopped being a CORS detail the day it also became Auth__AppUrl: without it a host with a
# working relay cannot invite an administrator, because the mail is nothing but a link. The
# server declines honestly rather than pretending, so this would not present as a crash — it
# would present as a customer who never receives his invite. A local rehearsal needs it for the
# same reason, and the generated .env.local has always set it.
required=(TEREN_STACK TEREN_DOMAIN TEREN_APP_ORIGIN TEREN_DB_NAME TEREN_DB_USER TEREN_DB_PASSWORD
          TEREN_STORAGE_ENDPOINT TEREN_STORAGE_ACCESS_KEY TEREN_STORAGE_SECRET_KEY
          TEREN_STORAGE_BUCKET)
if [ "$target" = "remote" ]; then
  required+=(TEREN_SSH_HOST TEREN_REMOTE_DIR)
fi
missing=()
for v in "${required[@]}"; do
  [ -n "${!v:-}" ] || missing+=("$v")
done
[ "${#missing[@]}" -eq 0 ] || die "these are unset in ${env_file}: ${missing[*]}"

# Warnings, not failures. Each of these leaves a working host that quietly cannot do its job,
# which is worse than a host that refuses to start — so say it out loud at deploy time.
[ -n "${TEREN_STT_AZURE_KEY:-}" ]     || note "WARNING: no Stt__Azure__Key — entries with audio will park in needs_review."
[ -n "${TEREN_ANTHROPIC_API_KEY:-}" ] || note "WARNING: no Anthropic__ApiKey — entries keep their transcript and park in needs_review."
[ -n "${TEREN_SMTP_HOST:-}" ]         || note "WARNING: no Reporting__Smtp__Host — confirmed entries stop at delivery_not_configured."
if [ -z "${TEREN_HANGFIRE_USER:-}" ] || [ -z "${TEREN_HANGFIRE_PASSWORD:-}" ]; then
  note "WARNING: no Hangfire dashboard credentials — /hangfire will refuse every request."
fi
# Auth__DeviceToken is one device's credential now, not the authentication system (ARCHITECTURE
# §12). Both states are legitimate and both are worth saying out loud, because each one is a
# 401 somebody would otherwise debug from the wrong end.
if [ -z "${TEREN_DEVICE_TOKEN:-}" ]; then
  note "NOTE: no Auth__DeviceToken — this host provisions no demo device. Phones activate at"
  note "      /auth/activate with a username and a code; nothing is baked into the bundle."
elif [ "${TEREN_DEVICE_TOKEN}" = "teren-dev-device-token-not-a-secret" ] && [ "$target" = "remote" ]; then
  note "WARNING: the demo device's token is the value published in this repository. Anyone who"
  note "         reads the repo holds a working credential to the demo company on this box."
fi
note "target=${target}  stack=${TEREN_STACK}  domain=${TEREN_DOMAIN}"

# ---------------------------------------------------------------------------------------------
# 2. Build
# ---------------------------------------------------------------------------------------------
if [ "$do_build" -eq 1 ]; then
  log "2/7 Building images"
  note "api: ${TEREN_API_IMAGE}"
  docker build "${build_args[@]}" -f "${here}/api.Dockerfile" -t "${TEREN_API_IMAGE}" "$repo"
  check_disk 3

  note "web: ${TEREN_WEB_IMAGE}"
  # No build args. The bundle carries no credential of any kind since D7/F9 — the device token
  # that used to be substituted here is a server-side value only (see web.Dockerfile).
  docker build "${build_args[@]}" -f "${here}/web.Dockerfile" \
    -t "${TEREN_WEB_IMAGE}" "$repo"
  check_disk 3
else
  log "2/7 Build skipped (--skip-build)"
fi

# ---------------------------------------------------------------------------------------------
# 3. Ship
#
# THE UNAUTOMATABLE SEAM, and it is only unautomatable because there is no host yet. Everything
# in this block is written but has never run: no VPS exists (C7). When one does, this is the
# first thing to exercise, and the first thing to distrust.
#
# No registry on purpose — a registry is a third account, a third bill and a third secret for a
# one-box deployment. `docker save | ssh docker load` needs nothing but ssh. If a second box ever
# appears, that is when a registry earns its keep.
# ---------------------------------------------------------------------------------------------
if [ "$target" = "remote" ]; then
  log "3/7 Shipping to ${TEREN_SSH_HOST}:${TEREN_REMOTE_DIR}"

  ssh "$TEREN_SSH_HOST" "mkdir -p '${TEREN_REMOTE_DIR}'" \
    || die "cannot ssh to ${TEREN_SSH_HOST}. Fix ssh access first; nothing has changed on the host."

  # Deploy files and the env file. tar over ssh rather than rsync: Git for Windows ships ssh but
  # not rsync, and the founder's machine is the one that runs this.
  note "deploy/ and .env"
  tar -C "$here" -czf - \
      docker-compose.prod.yml Caddyfile .env backup storage \
    | ssh "$TEREN_SSH_HOST" "tar -C '${TEREN_REMOTE_DIR}' -xzf -"

  note "images (this is the slow part: a few hundred MB over ssh)"
  docker save "${TEREN_API_IMAGE}" "${TEREN_WEB_IMAGE}" | gzip -1 \
    | ssh "$TEREN_SSH_HOST" "gunzip | docker load"

  compose_remote() {
    ssh "$TEREN_SSH_HOST" \
      "cd '${TEREN_REMOTE_DIR}' && docker compose --env-file .env -f docker-compose.prod.yml $*"
  }
else
  log "3/7 Ship skipped (local target — the images are already where they are needed)"
  compose_remote() { compose_local "$@"; }
fi

# ---------------------------------------------------------------------------------------------
# 4. Database up, and healthy, BEFORE migrating
# ---------------------------------------------------------------------------------------------
log "4/7 Database"
compose_remote up -d postgres
note "waiting for postgres to report healthy"
db_ready=0
for i in $(seq 1 60); do
  state="$(compose_remote ps --format '{{.Name}} {{.Health}}' 2>/dev/null | awk '/postgres/ {print $2}')" || true
  if [ "$state" = "healthy" ]; then
    note "postgres healthy after ${i}s"
    db_ready=1
    break
  fi
  sleep 1
done
[ "$db_ready" -eq 1 ] || die "postgres did not become healthy in 60s. Nothing was migrated."

# ---------------------------------------------------------------------------------------------
# 5. Migrate — explicit, separate, and before the new API serves a single request
# ---------------------------------------------------------------------------------------------
log "5/7 Migrations"
compose_remote --profile tools run --rm migrate
if [ "$do_seed" -eq 1 ]; then
  note "seeding demo data (idempotent)"
  compose_remote --profile tools run --rm seed
fi

# ---------------------------------------------------------------------------------------------
# 6. Start and verify
# ---------------------------------------------------------------------------------------------
log "6/7 Starting the application"
compose_remote up -d
compose_remote ps

# ---------------------------------------------------------------------------------------------
# 7. Bucket CORS — applied, every time, rather than remembered once
#
# The phone PUTs media straight to object storage, so the browser preflights that request against
# the bucket and refuses the upload unless the bucket answers. Nothing in the API can compensate.
# Running it on every deploy costs about a second and removes an entire class of "it worked on
# the laptop": the rules that are rehearsed locally are the rules that get applied to a managed
# bucket, from the same script and the same template.
#
# Fatal on failure, deliberately. A warning here would scroll past, and the symptom it predicts —
# uploads failing from the phone with nothing in the API log, because the API was never called —
# is one of the most expensive to diagnose in this system.
# ---------------------------------------------------------------------------------------------
if [ "$skip_cors" -eq 1 ]; then
  log "7/7 Bucket CORS skipped (--skip-cors)"
  note "The bucket's existing CORS configuration is now unverified. Uploads from a browser may fail."
elif [ "$target" = "local" ]; then
  log "7/7 Bucket CORS"
  "${here}/storage/apply-cors.sh" --env-file "$env_file" \
    || die "could not apply bucket CORS. The stack is up, but a browser will not be able to upload media to it. Re-run deploy/storage/apply-cors.sh, or pass --skip-cors if this store is configured elsewhere."
else
  log "7/7 Bucket CORS"
  # Run it on the host that can reach the bucket. For a managed store that is either machine;
  # for a self-hosted one inside the compose network it has to be the remote box.
  ssh "$TEREN_SSH_HOST" "cd '${TEREN_REMOTE_DIR}' && ./storage/apply-cors.sh --env-file .env" \
    || die "could not apply bucket CORS on ${TEREN_SSH_HOST}. The stack is up, but a browser will not be able to upload media to it."
fi

# /health/ready and not /health, deliberately. The liveness route is a constant: it answers `ok`
# on a host whose schema was never migrated, which is this repository's most repeated failure and
# exactly what a deploy is in a position to catch. Readiness asks both migration histories, both
# contexts and the job server. See src/Teren.Api/Health/ReadinessChecks.cs.
log "Verifying"
if [ "$target" = "local" ]; then
  # -k: Caddy signs with its own internal CA here. That is the one thing the local rehearsal
  # cannot prove about production, where the certificate is a real one from Let's Encrypt.
  probe=(curl -fsS -k --max-time 20 "https://localhost:8443/health/ready")
else
  probe=(curl -fsS --max-time 60 "https://${TEREN_DOMAIN}/health/ready")
fi

health=""
for i in $(seq 1 30); do
  if health="$("${probe[@]}" 2>/dev/null)"; then break; fi
  # A first deploy waits on ACME here; issuance normally takes seconds, occasionally longer.
  sleep 2
done
[ -n "$health" ] || die "the stack is up but /health/ready did not answer through the proxy. A 503 here names the check that failed — read it with: curl -k https://localhost:8443/health/ready, then: docker compose logs web api"
note "/health/ready through the proxy: ${health}"

log "Deployed"
if [ "$target" = "local" ]; then
  cat <<LOCALDONE
    app        https://localhost:8443           (self-signed: the browser will warn once)
    health     https://localhost:8443/health    liveness (a constant)
    ready      https://localhost:8443/health/ready   migrations, both contexts, the job server
    jobs       https://localhost:8443/hangfire  (${TEREN_HANGFIRE_USER})
    storage    https://localhost:9443           MinIO console http://127.0.0.1:9101
    mail       http://127.0.0.1:8125            every report lands here, nothing is sent
    stop       deploy/deploy.sh --target local --down
LOCALDONE
else
  cat <<REMOTEDONE
    app        https://${TEREN_DOMAIN}
    jobs       https://${TEREN_DOMAIN}/hangfire
    logs       ssh ${TEREN_SSH_HOST} "cd ${TEREN_REMOTE_DIR} && docker compose logs -f api"
    rollback   redeploy the previous commit; images are tagged, not versioned — see deploy/README.md
REMOTEDONE
fi
