// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teren.Infrastructure.Persistence;

#nullable disable

namespace Teren.Infrastructure.Migrations
{
    [DbContext(typeof(TerenDbContext))]
    [Migration("20260829201636_ProjectTimeZoneAndReportChecksum")]
    partial class ProjectTimeZoneAndReportChecksum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teren.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Teren.Core.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Corrected")
                        .HasColumnType("jsonb")
                        .HasColumnName("corrected");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<double?>("GpsAccuracyM")
                        .HasColumnType("double precision")
                        .HasColumnName("gps_accuracy_m");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RawTranscript")
                        .HasColumnType("text")
                        .HasColumnName("raw_transcript");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTime?>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Structure")
                        .HasColumnType("jsonb")
                        .HasColumnName("structure");

                    b.Property<Guid?>("SupersedesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_entry_id");

                    b.Property<string>("Weather")
                        .HasColumnType("jsonb")
                        .HasColumnName("weather");

                    b.HasKey("Id")
                        .HasName("pk_entry");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_entry_company_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_entry_status");

                    b.HasIndex("SupersedesEntryId")
                        .HasDatabaseName("ix_entry_supersedes_entry_id");

                    b.HasIndex("ProjectId", "EntryDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_entry_project_id_entry_date");

                    b.ToTable("entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_entry_corrected_schema_version", "corrected IS NULL OR jsonb_exists(corrected, 'schema_version')");

                            t.HasCheckConstraint("ck_entry_status", "status IN ('received','processing','awaiting_confirmation','needs_review','confirmed','reported')");

                            t.HasCheckConstraint("ck_entry_structure_schema_version", "structure IS NULL OR jsonb_exists(structure, 'schema_version')");
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upload_status");

                    b.HasKey("Id")
                        .HasName("pk_media");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_media_company_id");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("ix_media_entry_id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_object_key");

                    b.ToTable("media", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_kind", "kind IN ('audio','photo')");

                            t.HasCheckConstraint("ck_media_upload_status", "upload_status IN ('pending','uploaded','verified','failed')");
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Recipients")
                        .HasColumnType("jsonb")
                        .HasColumnName("recipients");

                    b.Property<string>("ReportLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sr")
                        .HasColumnName("report_language");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Europe/Belgrade")
                        .HasColumnName("time_zone");

                    b.Property<string>("Vocabulary")
                        .HasColumnType("jsonb")
                        .HasColumnName("vocabulary");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_project_company_id");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Teren.Core.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AttemptStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempt_started_at");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryDetail")
                        .HasColumnType("text")
                        .HasColumnName("delivery_detail");

                    b.Property<Guid?>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("PdfObjectKey")
                        .HasColumnType("text")
                        .HasColumnName("pdf_object_key");

                    b.Property<string>("PdfSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pdf_sha256");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Recipients")
                        .HasColumnType("jsonb")
                        .HasColumnName("recipients");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_report");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_report_company_id");

                    b.HasIndex("EntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_report_entry_id")
                        .HasFilter("entry_id IS NOT NULL");

                    b.HasIndex("ProjectId", "PeriodStart")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_report_project_id_period_start");

                    b.ToTable("report", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_kind", "kind IN ('daily','weekly')");

                            t.HasCheckConstraint("ck_report_sent_at", "(status = 'sent') = (sent_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_report_status", "status IN ('sending','sent','failed')");
                        });
                });

            modelBuilder.Entity("Teren.Core.Entities.Entry", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_company");

                    b.HasOne("Teren.Core.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_project");

                    b.HasOne("Teren.Core.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("SupersedesEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entry_supersedes_entry");
                });

            modelBuilder.Entity("Teren.Core.Entities.Media", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_company");

                    b.HasOne("Teren.Core.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_entry");
                });

            modelBuilder.Entity("Teren.Core.Entities.Project", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_company");
                });

            modelBuilder.Entity("Teren.Core.Entities.Report", b =>
                {
                    b.HasOne("Teren.Core.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_company");

                    b.HasOne("Teren.Core.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_report_entry");

                    b.HasOne("Teren.Core.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_project");
                });
#pragma warning restore 612, 618
        }
    }
}
